[package]
name = "bevy_actions"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "0.7.0"
serde = "1.0.133"
anyhow = "1.0.52"
bevy_actions_derive = { path = "derive" }
bevy = { version = "0.6.0", features = ["serialize"] }
