[package]
name = "bevy_actions_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.85"
ron = "0.7.0"
quote = "1.0.14"
find-crate = "0.6.3"
proc-macro2 = "1.0.36"
